apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-backend
  labels:
    app: guestbook
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
      tier: backend
  template:
    metadata:
      labels:
        app: guestbook
        tier: backend
    spec:
      containers:
      - name: backend
        image: guestbook-backend
        ports:
        - name: http-server
          containerPort: 8080
        - name: debug
          containerPort: 3000
        env:
        - name: PORT
          value: "8080"
        - name: GUESTBOOK_DB_ADDR
          value: guestbook-mongodb:27017
