apiVersion: v1
kind: Service
metadata:
  name: nodejs-guestbook-frontend
  labels:
    app: nodejs-guestbook
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: nodejs-guestbook
    tier: frontend
  ports:
  - port: 80
    targetPort: http-server