apiVersion: v1
kind: Service
metadata:
  name: node-guestbook-frontend
  labels:
    app: node-guestbook
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: node-guestbook
    tier: frontend
  ports:
  - port: 80
    targetPort: http-server