apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-guestbook-frontend
  labels:
    app: node-guestbook
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-guestbook
      tier: frontend
  template:
    metadata:
      labels:
        app: node-guestbook
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: node-guestbook-frontend
        ports:
        - name: http-server
          containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: GUESTBOOK_API_ADDR
          value: node-guestbook-backend:8080
