apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: python-guestbook-frontend
  labels:
    app: python-guestbook
    tier: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: python-guestbook
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: python-guestbook-frontend
        ports:
        - name: http-server
          containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: GUESTBOOK_API_ADDR
          value: python-guestbook-backend:8080
