# Generated by Django 2.2 on 2019-06-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ('author',),
            },
        ),
    ]
