# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# To learn more about the skaffold.yaml schema visit
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: frontend
build:
  # defines where to find the code at build time and where to push the resulting image
  artifacts:
      # To learn more about how Jib builds Java containers visit
      # https://github.com/GoogleContainerTools/jib
    - image: java-guestbook-frontend
      jib:
        project: frontend
      context: ../
# defines the Kubernetes manifests to deploy on each run
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/*.yaml
portForward:
  # Cloud Code automatically port forwards resources,
  # or users can define explicit port forwards here.
  # For more info, visit https://skaffold.dev/docs/pipeline-stages/port-forwarding/#UDPF
  - resourceType: service
    resourceName: java-guestbook-frontend
    port: 80
    localPort: 4503
profiles:
# use the cloudbuild profile to build images using Google Cloud Build
- name: cloudbuild
  build:
    googleCloudBuild: {}
# use the dockerfile profile to build images using Docker instead of Jib
- name: dockerfile
  build:
    artifacts:
      - image: java-guestbook-frontend
        context: .
        