# To learn more about the skaffold.yaml schema visit
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: frontend
build:
  # defines where to find the code at build time and where to push the resulting image
  artifacts:
  - image: python-guestbook-frontend
    context: .
# defines the Kubernetes manifests to deploy on each run
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/*.yaml
portForward:
  # Cloud Code automatically port forwards resources,
  # or users can define explicit port forwards here.
  # For more info, visit https://skaffold.dev/docs/pipeline-stages/port-forwarding/#UDPF
  - resourceType: service
    resourceName: python-guestbook-frontend
    port: 80
    localPort: 4503
profiles:
# use the cloudbuild profile to build images using Google Cloud Build
- name: cloudbuild
  build:
    googleCloudBuild: {}
    