apiVersion: v1
kind: Service
metadata:
  name: dotnet-guestbook-mongodb
  labels:
    app: dotnet-guestbook
    tier: db
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: dotnet-guestbook
    tier: db