apiVersion: skaffold/v2beta15
kind: Config
metadata:
  name: frontend
build:
  artifacts:
  - image: nodejs-guestbook-frontend
    context: .
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/guestbook-frontend.service.yaml
    - ./kubernetes-manifests/guestbook-frontend.deployment.yaml
  statusCheckDeadlineSeconds: 300
portForward:
  # Cloud Code automatically port forwards resources,
  # or users can define explicit port forwards here.
  # For more info, visit https://skaffold.dev/docs/pipeline-stages/port-forwarding/#UDPF
  - resourceType: service
    resourceName: nodejs-guestbook-frontend
    port: 80
    localPort: 4503
profiles:
# use the cloudbuild profile to build images using Google Cloud Build
- name: cloudbuild
  build:
    googleCloudBuild: {}
- name: buildpacks
  build:
    artifacts:
    - image: nodejs-guestbook-frontend
      context: .
      buildpacks:
        builder: "gcr.io/buildpacks/builder:v1"
