apiVersion: skaffold/v1alpha5
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - context: cmd/hello-world
      image: hello-world
deploy:
  kubectl:
    manifests:
      - kubernetes-manifests/**
profiles:
  - name: local
    build:
      local:
        push: false
