steps:
- id: Generate unique service name
  name: 'gcr.io/cloud-builders/gcloud:$_CLOUDSDK_VERSION'
  entrypoint: '/bin/bash'
  args:
  - '-c'
  - |
    random-string() {
        cat /dev/urandom | LC_CTYPE=C tr -dc 'a-z0-9' | head -c 15
    }
    echo $(random-string) > _RND
    echo "Cloud Run Service Name is $_SERVICE-$(cat _RND)"
  dir: '${_SAMPLE_DIR}'

- id: 'Code Style'
  name: 'node:12-slim'
  entrypoint: '/bin/bash'
  args:
  - '-c'
  - |
    npm install
    npm run lint
  dir: '${_SAMPLE_DIR}'

- id: 'Build Container Image'
  name: 'gcr.io/cloud-builders/docker:latest'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/${_SERVICE}:${COMMIT_SHA}', '.']
  dir: '${_SAMPLE_DIR}'

- id: 'Push Container Image'
  name: 'gcr.io/cloud-builders/docker:latest'
  args: ['push', 'gcr.io/${PROJECT_ID}/${_SERVICE}:${COMMIT_SHA}']

- id: Deploy to Cloud Run
  name: 'gcr.io/cloud-builders/gcloud:$_CLOUDSDK_VERSION'
  entrypoint: '/bin/bash'
  args:
  - '-c'
  - |
    gcloud run deploy $_SERVICE-$(cat _RND) \
     --image gcr.io/$PROJECT_ID/$_SERVICE:$COMMIT_SHA \
     --region $_REGION --platform managed --no-allow-unauthenticated \
     --service-account $_SERVICE_ACCOUNT
    gcloud run services add-iam-policy-binding $_SERVICE-$(cat _RND) \
     --region $_REGION --platform managed \
     --member serviceAccount:${_SERVICE_ACCOUNT} \
     --role roles/run.invoker
  dir: '${_SAMPLE_DIR}'

- id: 'Get Cloud Run URL'
  name: 'gcr.io/cloud-builders/gcloud:$_CLOUDSDK_VERSION'
  entrypoint: '/bin/bash'
  args:
  - '-c'
  - |
    get_url() {
        gcloud run services describe $_SERVICE-$(cat _RND) \
          --platform managed --region ${_REGION} \
          --format 'value(status.url)'
    }
    echo $(get_url) > _service_url
    echo "Cloud Run URL for $_SERVICE-$(cat _RND) is $(cat _service_url)"
  dir: '${_SAMPLE_DIR}'

- id: 'Get Identity Token'
  name: 'gcr.io/cloud-builders/gcloud:$_CLOUDSDK_VERSION'
  entrypoint: '/bin/bash'
  args:
  - '-c'
  - |
    echo "Getting identity token with service account $_SERVICE_ACCOUNT..."
    get_id_token() {
      curl -X POST -H "content-type: application/json" \
        -H "Authorization: Bearer $(gcloud auth print-access-token)" \
        -d "{\"audience\": \"$(cat _service_url)\"}" \
        "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/${_SERVICE_ACCOUNT}:generateIdToken" | \
        python3 -c "import sys, json; print(json.load(sys.stdin)['token'])"
    }
    echo $(get_id_token) > _id_token
  dir: '${_SAMPLE_DIR}'

- id: 'Integration Tests'
  name: 'node:12-slim'
  entrypoint: '/bin/bash'
  args:
  - '-c'
  - |
    SERVICE_URL=$(cat _service_url) TOKEN=$(cat _id_token) npm test
  dir: '${_SAMPLE_DIR}'

- id: 'Teardown'
  name: 'gcr.io/cloud-builders/gcloud:$_CLOUDSDK_VERSION'
  entrypoint: '/bin/bash'
  args:
  - '-c'
  - |
    set -x
    gcloud --quiet container images delete gcr.io/${PROJECT_ID}/${_SERVICE}:${COMMIT_SHA}
    gcloud --quiet run services delete $_SERVICE-$(cat _RND) --region ${_REGION} --platform managed
    set +x
    echo "View build details in the console: https://console.cloud.google.com/cloud-build/builds/${BUILD_ID}"
  dir: '${_SAMPLE_DIR}'

substitutions:
  _CLOUDSDK_VERSION: latest
  _REGION: us-central1
  _SERVICE: nodejs-cloud-run-hello-world
  _SAMPLE_DIR: nodejs/nodejs-cloud-run-hello-world