steps:
- id: 'create hello world k8s namespace'
  name: 'gcr.io/cloud-builders/kubectl'
  args: ['create','namespace','test-nodejs-helloworld-$BUILD_ID']
  waitFor: ['-'] # start immediately

- id: 'create guestbook k8s namespace'
  name: 'gcr.io/cloud-builders/kubectl'
  args: ['create','namespace','test-nodejs-guestbook-$BUILD_ID']
  waitFor: ['-'] # start immediatel
substitutions:
   _LANGUAGE: nodejs
   _TEMPLATE: hello-world 
options:
  env:
    # location/name of GKE cluster (used by all kubectl commands)
    - CLOUDSDK_COMPUTE_ZONE=us-central1-a
    - CLOUDSDK_CONTAINER_CLUSTER=staging    
    - SKAFFOLD_DEFAULT_REPO=gcr.io/$PROJECT_ID