# To learn more about the skaffold.yaml schema visit
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2beta4
kind: Config
build:
  artifacts:
  - image: go-guestbook-backend
    context: src/backend
  - image: go-guestbook-frontend
    context: src/frontend
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/*.service.yaml
    - ./kubernetes-manifests/*.deployment.yaml
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}

