apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
  - image: guestbook-backend
    context: src/backend
  - image: guestbook-frontend
    context: src/frontend
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/**
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}

