# To learn more about the skaffold.yaml schema visit
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2beta4
kind: Config
build:
  artifacts:
  - image: go-guestbook-backend
    context: .
    docker:
      dockerfile: src/backend/Dockerfile
      noCache: false
  - image: go-guestbook-frontend
    context: .
    docker:
      dockerfile: src/frontend/Dockerfile
      noCache: false
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/*.service.yaml
    - ./kubernetes-manifests/*.deployment.yaml
portForward:
  # Cloud Code automatically port forwards resources,
  # or users can define explicit port forwards here.
  # For more info, visit https://skaffold.dev/docs/pipeline-stages/port-forwarding/#UDPF
  - resourceType: service
    resourceName: go-guestbook-frontend
    port: 80
    localPort: 4503
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}

