# To learn more about the skaffold.yaml schema visit
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: backend
build:
  artifacts:
  - image: nodejs-guestbook-backend
    context: .
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/*.yaml
  statusCheckDeadlineSeconds: 300
profiles:
# use the cloudbuild profile to build images using Google Cloud Build
- name: cloudbuild
  build:
    googleCloudBuild: {}
- name: buildpacks
  build:
    artifacts:
    - image: nodejs-guestbook-backend
      context: .
      buildpacks:
        builder: "gcr.io/buildpacks/builder:v1"
        env:
        - GOOGLE_RUNTIME_VERSION=16.16.0
