apiVersion: v1
kind: Service
metadata:
  name: java-guestbook-backend
  labels:
    app: java-guestbook
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: java-guestbook
    tier: backend
  ports:
  - port: 8080
    targetPort: http-server
